services:
  # Backend API Service
  - type: web
    name: tadiran-warranty-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: tadiran-warranty-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
    autoDeploy: true
    rootDir: backend
    # Note: Custom domains require paid plans
    # domains:
    #   - api.tadiran.com
    
  # Frontend Admin Panel
  - type: web
    name: tadiran-warranty-admin
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://tadiran-warranty-api.onrender.com # Will be auto-generated URL
      - key: NODE_ENV
        value: production
    autoDeploy: true
    rootDir: admin
    # Note: Custom domains require paid plans
    # domains:
    #   - admin.tadiran.com

databases:
  - name: tadiran-warranty-db
    databaseName: tadiran_warranty
    user: tadiran_user
    plan: free

# Optional: Background workers or cron jobs
# - type: worker
#   name: tadiran-warranty-worker
#   env: node
#   buildCommand: npm install && npm run build
#   startCommand: npm run worker
#   rootDir: backend
#   envVars:
#     - key: NODE_ENV
#       value: production
#     - key: DATABASE_URL
#       fromDatabase:
#         name: tadiran-warranty-db
#         property: connectionString

# Optional: Cron jobs for cleanup, etc.
# - type: cron
#   name: warranty-cleanup
#   schedule: "0 2 * * *" # Daily at 2 AM
#   buildCommand: npm install && npm run build
#   startCommand: npm run cleanup
#   rootDir: backend
#   envVars:
#     - key: NODE_ENV
#       value: production
#     - key: DATABASE_URL
#       fromDatabase:
#         name: tadiran-warranty-db
#         property: connectionString
