services:
  # Backend API Service
  - type: web
    name: tadiran-warranty-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health    
    rootDir: backend


