# Exported from Render on 2025-06-17T16:16:04Z
services:
- type: web
  name: Tadiran-Invoice-Warranty-System
  runtime: node
  repo: https://github.com/Rom943/Tadiran-Invoice-Warranty-System
  plan: free
  region: frankfurt
  buildCommand: npm run build
  startCommand: npm start
  autoDeployTrigger: commit
  rootDir: backend
version: "1"
